package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("appversions", "resId", Appversions.class);
		arp.addMapping("groups", "grpId", Groups.class);
		arp.addMapping("logging", "logId", Logging.class);
		arp.addMapping("menu", "menuId", Menu.class);
		arp.addMapping("read_user", "id", ReadUser.class);
		arp.addMapping("resources", "resId", Resources.class);
		arp.addMapping("rich_media", "rmId", RichMedia.class);
		arp.addMapping("role", "roleId", Role.class);
		arp.addMapping("role_menu", "id", RoleMenu.class);
		arp.addMapping("user", "userId", User.class);
		arp.addMapping("user_group", "id", UserGroup.class);
		arp.addMapping("user_info", "userId", UserInfo.class);
		arp.addMapping("user_menu", "id", UserMenu.class);
		arp.addMapping("user_role", "id", UserRole.class);
	}
}

