package com.demo.common.model;

import com.demo.common.model.base.BaseAppversions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Appversions extends BaseAppversions<Appversions> {
	public static final Appversions dao = new Appversions();
}
