package com.demo.common.model;

import com.demo.common.model.base.BaseGroups;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Groups extends BaseGroups<Groups> {
	public static final Groups dao = new Groups();
}
