package com.demo.common.model;

import com.demo.common.model.base.BaseLogging;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logging extends BaseLogging<Logging> {
	public static final Logging dao = new Logging();
}
