package com.demo.common.model;

import com.demo.common.model.base.BaseReadUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReadUser extends BaseReadUser<ReadUser> {
	public static final ReadUser dao = new ReadUser();
}
