package com.demo.common.model;

import com.demo.common.model.base.BaseResources;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resources extends BaseResources<Resources> {
	public static final Resources dao = new Resources();
}
