package com.demo.common.model;

import com.demo.common.model.base.BaseRichMedia;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RichMedia extends BaseRichMedia<RichMedia> {
	public static final RichMedia dao = new RichMedia();
}
