package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRichMedia<M extends BaseRichMedia<M>> extends Model<M> implements IBean {

	public void setRmId(String rmId) {
		set("rmId", rmId);
	}

	public String getRmId() {
		return get("rmId");
	}

	public void setUserId(String userId) {
		set("userId", userId);
	}

	public String getUserId() {
		return get("userId");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setResIds(String resIds) {
		set("resIds", resIds);
	}

	public String getResIds() {
		return get("resIds");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setReadNumber(Integer readNumber) {
		set("readNumber", readNumber);
	}

	public Integer getReadNumber() {
		return get("readNumber");
	}

	public void setDatetime(java.util.Date datetime) {
		set("datetime", datetime);
	}

	public java.util.Date getDatetime() {
		return get("datetime");
	}

}
