package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public void setUserId(String userId) {
		set("userId", userId);
	}

	public String getUserId() {
		return get("userId");
	}

	public void setGender(String gender) {
		set("gender", gender);
	}

	public String getGender() {
		return get("gender");
	}

	public void setAge(Integer age) {
		set("age", age);
	}

	public Integer getAge() {
		return get("age");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setQq(String qq) {
		set("qq", qq);
	}

	public String getQq() {
		return get("qq");
	}

	public void setHeadId(String headId) {
		set("headId", headId);
	}

	public String getHeadId() {
		return get("headId");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setHeadP(String headP) {
		set("headP", headP);
	}

	public String getHeadP() {
		return get("headP");
	}

	public void setID(String ID) {
		set("ID", ID);
	}

	public String getID() {
		return get("ID");
	}

	public void setIDP0(String IDP0) {
		set("IDP0", IDP0);
	}

	public String getIDP0() {
		return get("IDP0");
	}

	public void setIDP1(String IDP1) {
		set("IDP1", IDP1);
	}

	public String getIDP1() {
		return get("IDP1");
	}

}
