package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMenu<M extends BaseUserMenu<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setMenuId(String menuId) {
		set("menuId", menuId);
	}

	public String getMenuId() {
		return get("menuId");
	}

	public void setUserId(String userId) {
		set("userId", userId);
	}

	public String getUserId() {
		return get("userId");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

}
