package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppversions<M extends BaseAppversions<M>> extends Model<M> implements IBean {

	public void setResId(String resId) {
		set("resId", resId);
	}

	public String getResId() {
		return get("resId");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setAppversions(String appversions) {
		set("appversions", appversions);
	}

	public String getAppversions() {
		return get("appversions");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

}
