package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserGroup<M extends BaseUserGroup<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setUserId(String userId) {
		set("userId", userId);
	}

	public String getUserId() {
		return get("userId");
	}

	public void setGrpId(String grpId) {
		set("grpId", grpId);
	}

	public String getGrpId() {
		return get("grpId");
	}

	public void setAliasName(String aliasName) {
		set("aliasName", aliasName);
	}

	public String getAliasName() {
		return get("aliasName");
	}

}
