package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleMenu<M extends BaseRoleMenu<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setMuenId(String muenId) {
		set("muenId", muenId);
	}

	public String getMuenId() {
		return get("muenId");
	}

	public void setRoleId(String roleId) {
		set("roleId", roleId);
	}

	public String getRoleId() {
		return get("roleId");
	}

}
